server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
weather:
  lfh:
    API_URL: http://apis.juhe.cn/simpleWeather/query
    API_KEY: 5087c268c591551f7ffdf4b06cd30fce
    CITY_NAME: "商丘"

wx:
  mp:
    app_id: h_9f5f3db43264
    secret: 225b13166e2904b81ebb6cb86e0b1616
    token: linfuhaoistoken
    aes-key: jlj8Z8LRARVmXCMq0Ng1FESyp3hptDzFzCSRnmGf1au