server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
weather:
  lfh:
    API_URL: http://apis.juhe.cn/simpleWeather/query
    API_KEY: 5087c268c591551f7ffdf4b06cd30fce
    CITY_NAME: "商丘"
wx:
  mp:
    app-id: wxda15605caa310c14
    secret: 56b04b1a4d89a7a482d6862af62a3fed
    token: linfuhaoistoken
    aes-key: